### ISSUE TITLE
TableView scrolls when you tap BxInputActionRow 

### ISSUE THREAD

**Issue by Sandiryakov** [ByteriX/BxInputController#1]
When you tap BxInputActionRow, BxInputController tries to center this row, which might not be the expected behavior. One possible workaround for this is overriding method updateInsets() of BxInputController.

**Comment by sofbix** [comment]
You must call super.updateCell() in overrided updateCell(), or use cell?.valueTextField.isEnabled = false.

In a future I'll rewrite BxInputActionRow, and throw textField from them.
