### ISSUE TITLE
Проблема с форматированием строк в BxInputFormattedTextRow 

### ISSUE THREAD

**Issue by Sandiryakov** [ByteriX/BxInputController#2]
Если в примере SimpleAllRowsController в поле phoneTextRow:

```
let phoneTextRow = BxInputFormattedTextRow(title: "phone value",
                                           subtitle: "only russian",
                                           placeholder: "(___)-___-__-__",
                                           prefix: "+7",
                                           format: "(###)-###-##-##")
```

вынести параметр format из инициализатора вот так:
```
let phoneTextRow = BxInputFormattedTextRow(title: "phone value",
                                           subtitle: "only russian",
                                           placeholder: "(___)-___-__-__",
                                           prefix: "+7")

...

override func viewDidLoad() {
   super.viewDidLoad()
   phoneTextRow.formattingTemplate = "(###)-###-##-##"
   ...
}
```
то форматирование работает неправильно:

![kapture 2018-08-28 at 16 12 59](https://user-images.githubusercontent.com/19505077/44722619-a905ee80-aade-11e8-856b-98506592c6b1.gif)

**Comment by sofbix** [comment]
Проблема была в BxTextField. При обновлении подов автоматически подтянется 1.7.2 версия, в которой все будет хорошо. Обращаю твое внимание, что при сокращении таким образом конструктора ты делаешь вызов другого конструктора, тем самым не инициализируешь необходимые детали: клавиатуру и ограниченный ввод символов, так что у тебя будет работать такой ввод все равно не правильно из-за возможности писать произвольные символы, смотри конструкторы.
